### ISSUE TITLE
Developer start-up guide

### ISSUE THREAD

**Issue by Alex-Gberg** [PedroS235/BICS-BOT#12]
To allow for more contribution there should be a start-up guide for interested developers. Something along the lines of this: https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/bot/.

The main steps/tasks are the following:
- [x] Create a test server template (a link to create a minimal mirror of the BiCS server that developers can use to test. It must include channels, roles, and any other element that is used by the bot)
- [x] Create a default config file containing IDs that can be copied and overridden by developers with their own IDs for guilds, channels, etc.
- [x] Create a README containing the steps needed to setup the dev environment. This includes starting the test server, creating and inviting a bot, altering the config, creating a .env file, and the git workflow (forking, pull requests, etc.).

**Comment by PedroS235** [comment]
Awesome! The server we already have one, however is not up to date to the current one. As for the roles, we are currnetly saving them in the server_ids
