### ISSUE TITLE
New command for Courses selection

### ISSUE THREAD

**Issue by PedroS235** [PedroS235/BICS-BOT#4]
Currently, the bot as no command to give the users the ability to allow them to choose specif courses. Instead, they can see every channel of their current year. 

The idea is to make use of the Select view to list the available courses and let users choose the course channel they want to see. The bot's job is to then assignt to the user the permission to view the desired courses channels

**Comment by PedroS235** [comment]
- [ ] Call to course command
- [ ] Get User Object (interaction.user)
- [ ] Pass GUILD object to function that returns a list of the user's enrolled courses (needs to be implemented)
- [ ] save enrolled courses into a var
- [ ] pass the enrolled var to the DropdownView()
- [ ] DropDownView passes to DropDownItems
- [ ] when creating DropDownItems options, verify if the course is in the enrolled var

**Comment by umutucak** [comment]
- [ ] Call to course command
- [ ] Get User Object (interaction.user)
- [ ] Pass GUILD object to function that returns a list of the user's enrolled courses (needs to be implemented)
- [ ] save enrolled courses into a var
- [ ] pass the enrolled var to the DropdownView()
- [ ] DropDownView passes to DropDownItems
- [ ] Check for enrolled courses while looping through all courses, add `default=True` parameter for courses that are enrolled in

**Comment by umutucak** [comment]
New steps:

- [ ] Print back the final chosen courses when user clicks `confirm`.
- [ ] Do not print back the dropdown menus when user clicks `cancel`.
- [ ] Print a cancellation confirmation, and the chosen courses when the user clicks `cancel`.

**Comment by umutucak** [comment]
Latest issue: [dropdown](https://docs.nextcord.dev/en/stable/api.html#nextcord.ui.Select) menu's chosen elements are supposed to be in the `values` property. However, `values` is empty.

**Comment by umutucak** [comment]
Value is only empty when no changes are made in a dropdown menu. In a normal use case it will not be empty. Either way, a disclaimer message has been added at the top of the prompt.

**Comment by umutucak** [comment]
New Issue: With 7a88b42958f70f026b3b3c10d02fba7099a654dc the command is finished, however, it is taking too long. The loop has to be optimized.

**Comment by PedroS235** [comment]
There are still bugs that need to be fixed. First bug is that the course web-developement-1 is not being detected or recognized. Secondly, the process of unrolling courses is not fully 100% working. For example, if no items are selected it either means all courses are unrolled or that the user just wants to stay with the same. This could be check by comparing the the preselected courses. if these are empty it means that all courses are unrolled. if not it means not changes will be made.
